spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jaysanddy/cloud-config.git
#          uri: https://gitee.com/zhongzunfa/spring-cloud-config.git
          search-paths: spring-cloud-config
  application:
    name: sc-config-git
server:
  port: 9090
